import { Badge } from "@/components/ui/badge";
import { Sparkles } from "lucide-react";
import storyVariantsMap, { type StoryVariant } from "@/data/storyNotificationsVariants";
import duaVariantsMap from "@/data/duaNotificationsVariants";

export type SmartVariant = StoryVariant;

/**
 * Smart Variants — pre-generated, constraint-verified Bengali notification
 * copies for each published story (title < 60 chars, body < 120 chars).
 * The copies were generated by the Smart Notification Generator from each
 * story's real title, moral, and content excerpt, so they are always truthful.
 */

export interface SmartVariantsPanelProps {
  slug: string | null;
  contentTitle: string | null;
  selectedVariant: number | null;
  onSelect: (variant: StoryVariant) => void;
}

export default function SmartVariantsPanel({
  slug,
  contentTitle,
  selectedVariant,
  onSelect,
}: SmartVariantsPanelProps) {
  const entry = slug
    ? ((storyVariantsMap as Record<string, any>)[slug] ??
       (duaVariantsMap as Record<string, any>)[slug] ??
       null)
    : null;
  const variants: StoryVariant[] = entry?.variants ?? [];
  const label =
    entry?.tone ??
    (slug ? "বাংলা নোটিফিকেশন সাজেশন" : "Smart Notification Suggestions");

  if (!slug || variants.length === 0) {
    return (
      <div className="rounded-lg border border-dashed bg-muted/20 p-4">
        <div className="flex items-center gap-2 mb-1">
          <Sparkles className="h-4 w-4 text-muted-foreground" />
          <p className="text-xs font-medium text-muted-foreground">
            Smart Notifications
          </p>
        </div>
        <p className="text-[11px] text-muted-foreground">
          {slug
            ? "এই content-এর জন্য সাজেস্টেড নোটিফিকেশন নেই — নিজে compose করুন বা পুরাতন টেক্সট ব্যবহার করুন।"
            : "Story বা Dua সিলেক্ট করলে এখানে ৪টি ready-to-send Bengali notification সাজেশন আসবে।"}
        </p>
      </div>
    );
  }

  return (
    <div className="rounded-lg border bg-background p-4">
      <div className="flex items-center justify-between gap-2 mb-2.5">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-primary" />
          <p className="text-xs font-semibold">Smart Notifications</p>
          <Badge variant="secondary" className="h-4 px-1.5 text-[9px] rounded-full">
            ৪টি সাজেশন
          </Badge>
        </div>
        <p className="text-[10px] text-muted-foreground max-w-[60%] text-right truncate" title={contentTitle ?? undefined}>
          {contentTitle}
        </p>
      </div>

      <p className="text-[10px] text-muted-foreground mb-3">
        ক্লিক করলে title ও message ফিল্ড অটো-ফিল হবে (title &lt; 60, body &lt; 120 chars, verified)। যেকোনোটা সিলেক্ট করে পছন্দমতো এডিট করতে পারবেন।
      </p>

      <div className="space-y-1.5">
        {variants.map((v, i) => {
          const active = selectedVariant === i;
          return (
            <button
              key={`${slug}-${i}`}
              type="button"
              onClick={() => onSelect(v)}
              className={`w-full rounded-md border px-2.5 py-2 text-left transition-colors ${
                active
                  ? "border-primary bg-primary/5"
                  : "border-border/60 bg-muted/20 hover:bg-muted/60 hover:border-primary/40"
              }`}
            >
              <div className="flex items-center gap-1.5 mb-0.5">
                <Badge
                  variant={active ? "default" : "secondary"}
                  className="h-3.5 px-1.5 text-[9px] rounded-full"
                >
                  {v.tone || `সাজেশন ${i + 1}`}
                </Badge>
              </div>
              <p className="text-xs font-medium leading-snug">{v.title}</p>
              <p className="text-[11px] text-muted-foreground leading-snug mt-0.5 line-clamp-2">
                {v.body}
              </p>
            </button>
          );
        })}
      </div>

      <p className="text-[10px] text-muted-foreground mt-2.5">
        {label}
      </p>
    </div>
  );
}
